FROM alpine:latest

RUN apk add --no-cache python python3-dev py-pip build-base libffi-dev openssl-dev libgcc --update sqlite \
    && pip3 install --upgrade pip 

#RUN apk add --update sqlite

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirements.txt                                                                            

EXPOSE 5000

ENTRYPOINT  ["python3"]

CMD ["run.py"]
